export const strings_eng = {
  username: 'Username',
  login: 'Login',
  password: 'Password',
  register: 'Register',
  email: 'Email',
  name: 'Name',
  donthaveanaccount: 'Dont have an account?',
  home: 'Home',
  explore: 'Explore',
  profile: 'Profile',
  views: 'Views',
  subscribers: 'Subscribers',
  editprofile: 'Edit profile',
  subscribe: 'Subscribe',
  unsubscribe: 'Unsubscribe',
  comments: 'Comments',
  comment: 'Comment',
  changephoto: 'Change photo',
  save: 'Save',
  error: 'Error',
};
